# Site settings
name: Noah Rogers
title: Holiday
description: A travel project
baseurl: "/holiday"
highlighter: pygments

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
