# Site settings
name: Noah Rogers
title: Holiday
description: A travel project
baseurl: "/holiday"

# Build settings
highlighter: rouge
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets
